# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: home-cluster
endpoint: https://192.168.1.110:6443
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.12.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.35.2
additionalMachineCertSans:
  - "192.168.1.110"
  - "127.0.0.1"
additionalApiServerCertSans:
  - "127.0.0.1"
cniConfig:
  name: none
patches:
  - "@patches/kubelet-certificates.yaml"
  - "@patches/kubePrism.yaml"
  - "@patches/containerd.yaml"
  - "@patches/sysctls.yaml"

controlPlane:
  patches:
    - "@patches/cluster.yaml"
    - "@patches/apiserver.yaml"
    - "@patches/etcd.yaml"
    - "@patches/talos-api-access.yaml"

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  patches:
    - "@patches/nfs.yaml"
    - "@patches/kernel-modules.yaml"

nodes:
  - hostname: bmax1-master
    ipAddress: 192.168.1.81
    controlPlane: true
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    installDiskSelector:
      serial: "0x6da3dcf4"
      size: "125074145280"
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:4c:2f:69:52"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        vip:
          ip: 192.168.1.110
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
  - hostname: soyo2-master
    ipAddress: 192.168.1.82
    controlPlane: true
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    installDiskSelector:
      size: "512110190592"
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:9d:87:ac:99"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        vip:
          ip: 192.168.1.110
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
  - hostname: soyo3-master
    ipAddress: 192.168.1.83
    controlPlane: true
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    installDiskSelector:
      size: "512110190592"
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:9d:87:26:a7"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        vip:
          ip: 192.168.1.110
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
  - hostname: hp-worker3
    ipAddress: 192.168.1.93
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    installDiskSelector:
      wwid: naa.5000039fd2d5861c
      model: "TOSHIBA DT01ACA0"
    controlPlane: false
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    nodeLabels:
      node.longhorn.io/create-default-disk: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "74:46:a0:90:26:0f"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: disk.model == "SanDisk SSD PLUS" && !system_disk
          minSize: "200GiB"
          grow: false
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/mnt/longhorn
                type: bind
                source: /var/mnt/longhorn
                options:
                  - bind
                  - rshared
                  - rw
  - hostname: hp-worker2
    ipAddress: 192.168.1.92
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    installDiskSelector:
      wwid: naa.50014ee6597e703e
      model: "WDC WD10JPVX-22J"
    controlPlane: false
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    nodeLabels:
      node.longhorn.io/create-default-disk: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "10:60:4b:73:34:97"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: disk.model == "Apacer AS340 240" && !system_disk
          minSize: "200GiB"
          grow: false
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/mnt/longhorn
                type: bind
                source: /var/mnt/longhorn
                options:
                  - bind
                  - rshared
                  - rw
  - hostname: hp-worker1
    ipAddress: 192.168.1.91
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    installDiskSelector:
      model: "LITEONIT LCS-256"
    controlPlane: false
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c4:65:16:16:e2:b8"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
  - hostname: localstorage-worker1
    ipAddress: 192.168.1.101
    nameservers:
      - "192.168.1.139"
      - "1.1.1.1"
    installDiskSelector:
      model: "M.2 SSD 512GB"
    controlPlane: false
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/openebs/local
                type: bind
                source: /var/openebs/local
                options: ["bind", "rshared", "rw"]
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:4c:73:3b:3b"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        mtu: 1500
    disableSearchDomain: true
    machineSpec:
      mode: metal
      arch: amd64
