# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/kagent.dev/remotemcpserver_v1alpha2.json
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: flux-mcp
spec:
  description: Flux Operator MCP Server
  protocol: STREAMABLE_HTTP
  url: http://flux-mcp-flux-operator-mcp.automation.svc.cluster.local:9090/mcp
