# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: akeyless-to-s3
spec:
  image: ghcr.io/jdavid77/akeyless-to-s3
  interval: 5m
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: akeyless-to-s3
spec:
  imageRepositoryRef:
    name: akeyless-to-s3
  filterTags:
    pattern: '^v\d{4}\.\d{2}\.\d{2}$'
  policy:
    alphabetical:
      order: asc
