# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium-policy-agent
  - ./flux-agent
  - ./k8s-agent
  - ./promql-agent
