serviceMonitor:
  create: true
web:
  networkPolicy:
    create: false
  httpRoute:
    enabled: true
    parentRefs:
      - name: internal
        namespace: network
        sectionName: websecure
    hostnames:
      - flux.jnobrega.com