apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}
spec:
  cooldownPeriod: ${COOLDOWN_PERIOD:=300}
  minReplicaCount: ${MIN_REPLICAS:=0}
  maxReplicaCount: ${MAX_REPLICAS:=1}
  advanced:
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ${CONTROLLER:=Deployment}
    name: ${APP}
  triggers: []
