# Renovate Types
- name: renovate/container
  color: "8250df"
- name: renovate/github-action
  color: "8250df"
- name: renovate/github-release
  color: "8250df"
- name: renovate/helm
  color: "8250df"
# Semantic Types
- name: type/digest
  color: "29b6f6"
- name: type/patch
  color: "1976d2"
- name: type/minor
  color: "43a047"
- name: type/major
  color: "e53935"
