# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret pipelines-as-code-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: github-application-id
      remoteRef:
        key: /github/tekton-app-id
    - secretKey: github-private-key
      remoteRef:
        key: /github/tekton-app-key
    - secretKey: webhook.secret
      remoteRef:
        key: /github/tekton-webhook-secret
