# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: zot
      version: 0.1.106
      sourceRef:
        kind: HelmRepository
        name: zot-charts
        namespace: flux-system
      interval: 15m
  values:
    replicaCount: 3
    mountConfig: true
    configFiles:
      config.json: |
        {
          "distSpecVersion": "1.1.1",
          "storage": {
            "rootDirectory": "/tmp/zot",
            "gc": true,
            "dedupe": false,
            "storageDriver": {
              "name": "s3",
              "region": "us-east-1",
              "bucket": "zot",
              "regionendpoint": "http://garage.storage.svc.cluster.local:3900",
              "secure": false,
              "skipverify": true
            }
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "externalUrl": "https://registry.jnobrega.com",
            "auth": {
              "htpasswd": {
                "path": "/secret/htpasswd"
              },
              "openid": {
                "providers": {
                  "oidc": {
                    "credentialsFile": "/oidc/oidc-credentials.json",
                    "name": "Authentik SSO",
                    "issuer": "https://auth.jnobrega.com/application/o/Zot/",
                    "keypath": "",
                    "scopes": ["openid", "profile", "email", "groups"]
                  }
                }
              }
            }
          },
          "log": {
            "level": "info"
          },
          "extensions": {
            "ui": { "enable": true },
            "search": { "enable": true },
            "scrub": { "enable": true, "interval": "24h" }
          }
        }

    mountSecret: true
    secretFiles:
      htpasswd: |-
        admin:$2y$05$PAt5S8lT65jElESxVpaH/uzyFBgbAkRETa5sl7BT94ong0iqfhcHu

    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: zot-s3
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: zot-s3
            key: AWS_SECRET_ACCESS_KEY

    service:
      type: ClusterIP

    httproute:
      enabled: true
      parentRefs:
        - name: internal
          namespace: network
          sectionName: websecure
      hostnames:
        - "registry.jnobrega.com"
      rules:
        - matches:
          - path:
              type: PathPrefix
              value: /
          sessionPersistence:
            sessionName: zot-registry-session
            type: Cookie
            absoluteTimeout: 30m
            cookieConfig:
              lifetimeType: Permanent


    persistence: false

    # Extra Volume Mounts
    extraVolumeMounts:
      - name: oidc-credentials
        mountPath: /oidc/oidc-credentials.json
        subPath: oidc-credentials.json
        readOnly: true

    # Extra Volumes
    extraVolumes:
      - name: oidc-credentials
        secret:
          secretName: zot-oidc-secret