[tools]
helm = "latest"
sops = "latest"
age = "latest"
terraform = "latest"
"aqua:kubectl" = "1.36.2"
"aqua:siderolabs/talos" = {version = "latest", exe = "talosctl"}
"aqua:budimanjojo/talhelper" = "latest"
"aqua:kustomize" = "latest"
"aqua:fluxcd/flux2" = "2.9.1"
"aqua:go-task/task" = "latest"
