fail_fast: false
repos:
  - repo: https://github.com/onedr0p/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
        exclude: k8s/apps/monitoring/grafana-operator/instance/service-account-patch.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.244.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        files: ^terraform/
