apiVersion: v1
kind: Service
metadata:
  name: valkey-substrate-svc
  namespace: ate-system
spec:
  selector:
    valkey.io/cluster: substrate
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
