apiVersion: v1
kind: Service
metadata:
  name: dragonfly-${APP}-headless
spec:
  clusterIP: None
  selector:
    app: dragonfly-${APP}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: admin
      port: 9999
      targetPort: 9999
