# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ScaledObject
    patch: |
      - op: add
        path: /spec/triggers/-
        value:
          name: trig_postgres
          type: prometheus
          metadata:
            serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
            query: max_over_time(probe_success{instance=~".+:5432"}[1m])
            threshold: "1"
            ignoreNullValues: "0"
