apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: grimmory
  namespace: flux-system
spec:
  image: registry.jnobrega.com/mirror/grimmory-tools/grimmory
  interval: 5m
  provider: generic
  secretRef:
    name: zot-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: &repo grimmory
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: *repo
  policy:
    semver:
      range: '>=2.0.0'
