# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - akeyless-to-s3.yaml
  - curve-tracker.yaml
  - mealie-mcp-ts.yaml
  - grimmory.yaml
  - live-metrics.yaml
  - rendercv.yaml
  - ryanair-api.yaml
  - shelfmark.yaml
