# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  maxHistory: 2
  values:

    excludeNamespaces: "kube-system,flux-system"

    operator:
      replicas: 1
      scanJobsConcurrentLimit: 1
      scanJobTTL: 30s
      scanJobTimeout: "20m"
      builtInTrivyServer: true
      vulnerabilityScannerScanInterval: "24h"
      configAuditScannerScanInterval: "24h"
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      annotations:
        reloader.stakater.com/auto: "true"
      privateRegistryScanSecretsNames: 
        "storage": "zot-registry-secret"
    
    alternateReportStorage:
      enabled: true
      mountPath: "/mnt/data/trivy-operator"
      volumeName: "trivy-operator-pvc"
      storage: "10Gi"
      # -- storageClassName for the PVC (optional, uses cluster default if not specified)
      storageClassName: "openebs-hostpath"
      podSecurityContext:
        runAsUser: 10000
        fsGroup: 10000

    trivy:
      debug: true
      slow: true
      ignoreUnfixed: true
      mode: ClientServer
      severity: HIGH,CRITICAL
      storageClassEnabled: false
      resources:
        limits:
          memory: 1Gi
        
    nodeSelector:
      kubernetes.io/hostname: localstorage-worker1

    trivyOperator:
      skipResourceByLabels: app.kubernetes.io/created-by=volsync

    # https://github.com/aquasecurity/trivy-operator/issues/2566
    nodeCollector:
      useNodeSelector: false
      volumeMounts:
        - mountPath: /var/lib/etcd
          name: var-lib-etcd
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: var-lib-kubelet
          readOnly: true
        - mountPath: /var/lib/kube-scheduler
          name: var-lib-kube-scheduler
          readOnly: true
        - mountPath: /var/lib/kube-controller-manager
          name: var-lib-kube-controller-manager
          readOnly: true
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: /var/lib/etcd
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: var-lib-kube-scheduler
          hostPath:
            path: /var/lib/kube-scheduler
        - name: var-lib-kube-controller-manager
          hostPath:
            path: /var/lib/kube-controller-manager

    serviceMonitor:
      enabled: true
