# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  maxHistory: 2
  values:

    excludeNamespaces: "kube-system"

    operator:
      logDevMode: true
      replicas: 1
      scanJobsConcurrentLimit: 3
      scanJobTTL: 30s
      scanJobTimeout: "10m"
      builtInTrivyServer: true
      vulnerabilityScannerScanInterval: "24h"
      configAuditScannerScanInterval: "24h"
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      annotations:
        reloader.stakater.com/auto: "true"

    trivy:
      debug: true
      slow: true # flag is to use less CPU/memory for scanning though it takes more time than normal scanning
      ignoreUnfixed: true
      mode: Standalone
      severity: HIGH,CRITICAL
      storageClassEnabled: false # ephemeral storage
      resources:
        limits:
          cpu: 500m
          memory: 1Gi

    nodeCollector:
      volumeMounts:
        - name: etc-os-release
          mountPath: /host/etc/os-release
          readOnly: true
      volumes:
        - name: etc-os-release
          hostPath:
            path: /etc/os-release

    serviceMonitor:
      enabled: true
