# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  maxHistory: 2
  values:

    excludeNamespaces: "kube-system"

    operator:
      replicas: 1
      scanJobsConcurrentLimit: 1
      scanJobTTL: 30s
      scanJobTimeout: "20m"
      builtInTrivyServer: true
      vulnerabilityScannerScanInterval: "24h"
      configAuditScannerScanInterval: "24h"
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      annotations:
        reloader.stakater.com/auto: "true"
      privateRegistryScanSecretsNames: 
        "storage": "zot-registry-secret"

    trivy:
      debug: true
      slow: true # flag is to use less CPU/memory for scanning though it takes more time than normal scanning
      ignoreUnfixed: true
      mode: CLientServer
      severity: HIGH,CRITICAL
      storageClassEnabled: false # ephemeral storage
      resources:
        limits:
          memory: 1Gi

    trivyOperator:
      skipResourceByLabels: app.kubernetes.io/created-by=volsync

    nodeCollector:
      volumeMounts:
        - name: etc-os-release
          mountPath: /host/etc/os-release
          readOnly: true
      volumes:
        - name: etc-os-release
          hostPath:
            path: /etc/os-release
            
    serviceMonitor:
      enabled: true
