# TODO
apiVersion: portager.portager.io/v1alpha1
kind: ImageSync
metadata:
  name: curve-tracker
  namespace: storage
spec:
  schedule: "0 0 * * *"
  source:
    registry: ghcr.io/jdavid77
    authSecretRef:
      name: gh-secret
      namespace: default
  destination:
    registry: registry.jnobrega.com
    auth:
      method: secret
      secretRef:
        name: zot-registry-secret
    repositoryPrefix: mirror
  createDestinationRepos: true
  images:
    - name: curve-tracker
      semver: ">= 1.0.0"
      maxTags: 5