---
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  feature-gates: GracefulNodeShutdown=true,ClusterTrustBundle=true,ClusterTrustBundleProjection=true,PodCertificateRequest=true
config:
  maxPods: 150