apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: zot-ha
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  wait: true
  inputs:
    - name: zot-ha-1
    - name: zot-ha-2
  resourcesTemplate: |
    ---
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: << inputs.name >>
      namespace: storage
    spec:
      interval: 15m
      chart:
        spec:
          chart: zot
          version: 0.1.98
          sourceRef:
            kind: HelmRepository
            name: zot-charts
            namespace: flux-system
          interval: 15m
      values:
        mountConfig: true
        configFiles:
          config.json: |
            {
              "distSpecVersion": "1.1.1",
              "storage": {
                "rootDirectory": "/var/lib/registry",
                "gc": true,
                "gcDelay": "1h",
                "gcInterval": "24h"
              },
              "http": {
                "address": "0.0.0.0",
                "port": "5000",
                "auth": {
                  "htpasswd": {
                    "path": "/secret/htpasswd"
                  }
                },
                "accessControl": {
                  "repositories": {
                    "**": {
                      "policies": [
                        {
                          "users": ["admin"],
                          "actions": ["read", "create", "update"]
                        }
                      ],
                      "anonymousPolicy": []
                    }
                  }
                }
              },
              "log": {
                "level": "info"
              },
              "extensions": {
                "ui": {
                  "enable": true
                },
                "search": {
                  "enable": true
                }
              }
            }

        mountSecrets: true
        secretFiles:
          htpasswd: |-
            admin:$2y$05$DbI9Wqdhiuw27TuarKdREufBB0TxOFbC.eeytixQvyYNCvsAp1/uG

        persistence: true
        pvc:
          create: true
          accessModes:
            - ReadWriteOnce
          storage: 50Gi
          storageClassName: longhorn-zot

      valuesFrom:
        - kind: Secret
          name: zot-secret
          valuesKey: BASIC_AUTH_HEADER
          targetPath: authHeader

    <<- end >>
