# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret zot-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        BASIC_AUTH_HEADER: "{{ .BASIC_AUTH_HEADER | b64enc }}"
        PASSWORD: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: /zot/auth
