# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: x509-certificate-exporter
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: x509-certificate-exporter
    namespace: flux-system
  values:
    image:
      registry: quay.io
    prometheusRules:
      warningDaysLeft: 14
      criticalDaysleft: 7
    grafana:
      createDashboard: true
