originRequest:
  originServerName: jnobrega.com
  http2Origin: true
ingress:
  - hostname: "jnobrega.com"
    service: https://external.network.svc.cluster.local:443
  - hostname: "*.jnobrega.com"
    service: https://external.network.svc.cluster.local:443
  - service: http_status:404
