apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secret
  namespace: default
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /linkding/super-user
      metadataPolicy: None
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: linkding-secret
    template:
      engineVersion: v2
      mergePolicy: Replace