image:
  longhorn:
    instanceManager:
      tag: v1.11.0-hotfix-1
    manager:
      tag: v1.11.0-hotfix-1
metrics:
  serviceMonitor:
    enabled: true
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain
  defaultNodeSelector:
    enable: true
    selector: storage
defaultSettings:
  taintToleration: "node=storage:NoSchedule" 
  defaultReplicaCount: 2
  defaultDataPath: /var/mnt/longhorn
  autoCleanupSystemGeneratedSnapshot: true
  backupstorePollInterval: 0
  createDefaultDiskLabeledNodes: true
  restoreVolumeRecurringJobs: true
  storageMinimalAvailablePercentage: 0
  storageReservedPercentageForDefaultDisk: 5
  guaranteedEngineManagerCPU: 20
  guaranteedReplicaManagerCPU: 20
  orphanAutoDeletion: true
  concurrentAutomaticEngineUpgradePerNodeLimit: 3
  defaultLonghornStaticStorageClass: longhorn
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  upgradeChecker: false