## yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kromgo
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: kromgo
    namespace: flux-system
  values:
    existingConfigMap: kromgo-configmap
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    serviceAccount:
      create: false
    httpRoute:
      enabled: true
      parentRefs:
        - name: external
          namespace: network
          sectionName: websecure
      hostnames:
        - kromgo.jnobrega.com
      matches:
        - path:
            type: PathPrefix
            value: /
    monitoring:
      serviceMonitor:
        enabled: true
