# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kubernetes-live-metrics-dashboard-backend
spec:
  image: ghcr.io/jdavid77/kubernetes-live-metrics-dashboard-backend
  interval: 5m
  provider: generic
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kubernetes-live-metrics-dashboard-frontend
spec:
  image: ghcr.io/jdavid77/kubernetes-live-metrics-dashboard-frontend
  interval: 5m
  provider: generic
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagepolicy_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: &repo kubernetes-live-metrics-dashboard-backend
spec:
  imageRepositoryRef:
    name: *repo
  filterTags:
    pattern: '^v\d{4}\.\d{2}\.\d{2}\.\d{2}$'
  policy:
    alphabetical:
      order: asc
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagepolicy_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: &repo kubernetes-live-metrics-dashboard-frontend
spec:
  imageRepositoryRef:
    name: *repo
  filterTags:
    pattern: '^v\d{4}\.\d{2}\.\d{2}\.\d{2}$'
  policy:
    alphabetical:
      order: asc
