# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  values:
    controllers:
      valkey:
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 9.0.0-alpine3.22@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b
      server:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: immich-secret
          configmap.reloader.stakater.com/reload: immich-configmap
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: immich-secret
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.0.1@sha256:46dedfc5848f7313bd6b584ea9f2648057430307aad6de56de968f6710a72cae
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1002
            runAsGroup: 100
            runAsNonRoot: true
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379
    route:
      frontend:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - photos.jnobrega.com
        rules:
          - backendRefs:
              - name: immich-server
                port: *port
    persistence:
      matplotlib:
        type: emptyDir
        globalMounts:
          - path: /config/matplotlib
      library:
        type: nfs
        server: 192.168.1.84
        path: /photos
        globalMounts:
          - path: /usr/src/app/upload
      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
