apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: media
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /postgres/vector
      metadataPolicy: None
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /immich/jwt
      metadataPolicy: None
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: immich-secret
    template:
      data:
        DB_DATABASE_NAME: immich
        DB_HOSTNAME: 192.168.1.84
        DB_PASSWORD: '{{ .POSTGRES_SUPER_PASS }}'
        DB_USERNAME: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_DBNAME: immich
        INIT_POSTGRES_HOST: 192.168.1.84
        INIT_POSTGRES_PASS: '{{ .POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_PORT: "6001"
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .POSTGRES_SUPER_USER }}'
        JWT_SECRET: '{{ .JWT_SECRET }}'
      engineVersion: v2
      mergePolicy: Replace