apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - adventurelog/ks.yaml
  - curve-tracker/ks.yaml
  - excalidash/ks.yaml
  - filebrowser/ks.yaml
  - linkding/ks.yaml
  - littlelink/ks.yaml
  - live-metrics/ks.yaml
  - mealie/ks.yaml
  - morphos/ks.yaml
  # - redlib/ks.yaml
  - renderercv/ks.yaml
  - ryanair-api/ks.yaml
  - wallos/ks.yaml
  - whoami/ks.yaml

components:
  - ../../components/alerts/alertmanager
