# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent-crds
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/kagent/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kagent-crds
      namespace: automation
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 15m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/kagent/app
  prune: true
  dependsOn:
    - name: kagent-crds
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kagent
      namespace: automation
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 15m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kagent-remote-mcps
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/kagent/remote-mcps
  prune: true
  dependsOn:
    - name: kagent-crds
    - name: kagent
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 15m
