# Still needed apparently
apiVersion: v1
kind: ConfigMap
metadata:
  name: ate-api-authentication
  namespace: ate-system
data:
  authentication.yaml: |
    actorIdentityJWTProvider: kubernetes
    jwtProviders:
    - name: kubernetes
      issuer: https://192.168.1.110:6443
      audiences: [api.ate-system.svc]
      certificateAuthorityFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      discoveryTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
