# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: backup
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: volsync
    namespace: flux-system
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
