---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvme_tcp
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: vfio_pci
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: uio_pci_generic
