# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp
spec:
  mcp:
    targets:
      - name: flux
        static:
          host: flux-mcp.automation.svc.cluster.local
          port: 9090
          protocol: StreamableHTTP
      - name: kubernetes
        static:
          host: kubernetes-mcp.automation.svc.cluster.local
          port: 8080
          protocol: StreamableHTTP
      - name: n8n
        static:
          policies:
            auth:
              secretRef:
                name: n8n-mcp-auth
          host: n8n-mcp.automation.svc.cluster.local
          port: 3000
          protocol: StreamableHTTP
