apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - _folder.yaml
replacements:
  - _source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - _select:
          kind: GrafanaFolder
        fieldPaths:
          - _metadata.name
  - _source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - _select:
          kind: GrafanaFolder
        fieldPaths:
          - _spec.title
