apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-events
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: &name otel-collector-events
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: observability
roleRef:
  kind: ClusterRole
  name: *name
  apiGroup: rbac.authorization.k8s.io
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-events
spec:
  managementState: managed
  upgradeStrategy: automatic
  mode: deployment
  serviceAccount: otel-collector-events
  ports:
    - name: health
      port: 13113
  env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config:
    receivers:
      k8s_events:
        auth_type: serviceAccount
    processors:
      batch: {}
      groupbyattrs:
        keys:
          - k8s.event.reason
          - k8s.object.name
          - k8s.namespace.name
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      debug:
        verbosity: detailed
      otlphttp/loki:
        endpoint: http://loki-gateway.monitoring/otlp
    service:
      pipelines:
        logs:
          receivers: [k8sobjects]
          processors: [batch, groupbyattrs, memory_limiter]
          exporters: [otlphttp/loki, debug]
