apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-github-collector
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jnobrega-bot-pem
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: jnobrega-bot-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: /github/jnobrega-bot-key
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: jnobrega-bot-auth-token
spec:
  appID: "1087240"
  installID: "62936655"
  auth:
    privateKey:
      secretRef:
        name: jnobrega-bot-pem
        key: private_key_pem
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  refreshInterval: 1m
  target:
    name: github-token
    creationPolicy: Owner
    deletionPolicy: "Delete"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: jnobrega-bot-auth-token
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-github-collector
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-github-collector
  endpoints:
    - port: prometheus
      path: /metrics
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-github
spec:
  managementState: managed
  upgradeStrategy: automatic
  mode: deployment
  serviceAccount: otel-github-collector
  ports:
    - name: prometheus
      port: 9464
  podAnnotations:
    reloader.stakater.com/auto: "true"
  env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-token
          key: token
  config:
    extensions:
      bearertokenauth/github:
        token: ${env:GITHUB_TOKEN}
    receivers:
      github:
        initial_delay: 1s
        # watch out for github rate limit
        collection_interval: 300s
        scrapers:
          scraper:
            timeout: 60s
            github_org: Jdavid77
            search_query: "repo:Jdavid77/home-cluster"
            auth:
              authenticator: bearertokenauth/github
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      filter/github:
        metrics:
          include:
            match_type: strict
            metric_names:
              - vcs_change_count
              - vcs_ref_count
              - vcs_change_duration_seconds
              - vcs_change_time_to_merge_seconds
              - vcs_ref_time_seconds
    exporters:
      prometheus:
        endpoint: 0.0.0.0:9464
    service:
      extensions: [bearertokenauth/github]
      pipelines:
        metrics:
          receivers: [github]
          processors: [memory_limiter, filter/github, batch]
          exporters: [prometheus]

