apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-filelog-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-filelog-collector
rules:
  - apiGroups: [""]
    resources: [pods, namespaces, nodes, services, endpoints]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [replicasets, deployments, daemonsets, statefulsets]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [cronjobs, jobs]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: &name otel-filelog-collector
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: *name
  apiGroup: rbac.authorization.k8s.io
---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-filelog
spec:
  managementState: managed
  upgradeStrategy: automatic
  mode: daemonset
  serviceAccount: otel-filelog-collector
  ports:
    - name: health
      port: 13113
  env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config:
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/opentelemetry-collector/*.log
        include_file_path: true
        include_file_name: false
        retry_on_failure:
          enabled: true
        start_at: end
        operators:
          - id: container-parser
            max_log_size: 102400
            type: container
          - id: json-parser
            on_error: send
            type: json_parser
          - id: severity-parser
            on_error: send
            parse_from: body.level
            type: severity_parser
    processors:
      batch: {}
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.node.name
            - k8s.deployment.name
            - k8s.daemonset.name
            - k8s.statefulset.name
            - k8s.cronjob.name
            - service.namespace
            - service.name
          otel_annotations: true
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    exporters:
      otlphttp/loki:
        endpoint: http://loki-gateway.monitoring/otlp
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [otlphttp/loki]
  tolerations:
    - key: node.kubernetes.io/dedicated
      operator: Equal
      value: localstorage
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumeMounts:
    - name: pods
      mountPath: /var/log/pods
      readOnly: true
  volumes:
    - name: pods
      hostPath:
        path: /var/log/pods
