# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chart:
    spec:
      chart: ./charts/tekton-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: tekton
        namespace: flux-system
      interval: 10m
  values:
    installCRDs: true
    webhook:
      image:
        tag: v0.79.1
    operator:
      image:
        tag: v0.79.1
      autoInstallComponents: false
      deployment:
        initContainers:
          enabled: true
          containers:
            - envFrom:
                - secretRef:
                    name: tekton-results-postgres
              image: ghcr.io/home-operations/postgres-init:18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
              name: init-db
    service:
      createServiceMonitor: false
    nodeSelector:
      kubernetes.io/hostname: localstorage-worker1
