apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: development
spec:
  discoveryFilters:
    - "Jdavid77/*"
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: '[{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"}]'
  image: ghcr.io/renovatebot/renovate:43.214.6
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 */12 * * * # Run every 12 hours
  secretRef: jnobrega-bot-auth-token
  webhook:
    enabled: false
  provider:
    name: github
    endpoint: https://api.github.com
