# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adventurelog
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  values:
    controllers:
      adventurelog:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
              pullPolicy: IfNotPresent
            envFrom: &secret
              - secretRef:
                  name: adventurelog-secret
        containers:
          frontend:
            image:
              repository: ghcr.io/seanmorley15/adventurelog-frontend
              tag: latest@sha256:8c9dde5dae9daeed2622ca6c591f378211aa13b5368f2046cf149a8e229bfced
            env:
              PUBLIC_SERVER_URL: "http://adventurelog.default.svc.cluster.local:8000"
              BODY_SIZE_LIMIT: Infinity
              ORIGIN: "https://adventurelog.jnobrega.com"
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
          server:
            image:
              repository: ghcr.io/seanmorley15/adventurelog-backend
              tag: latest@sha256:8bafac63e5afa9fe6c80136b8a7c3798c2aa620225814f93476e2651569f87b9
            env:
              PUBLIC_URL: https://adventurelog-backend.jnobrega.com
              FRONTEND_URL: https://adventurelog.jnobrega.com
              CSRF_TRUSTED_ORIGINS: https://adventurelog-backend.jnobrega.com,https://adventurelog.jnobrega.com
              DEBUG: "true"
              DJANGO_ADMIN_USERNAME: admin
              ENABLE_RATE_LIMITS: "true"
            envFrom: *secret
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 125m
                memory: 500Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &frontend-port 3000
          base:
            port: &server-port 8000
    route:
      frontend:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - adventurelog.jnobrega.com
        rules:
          - backendRefs:
              - name: *app
                port: *frontend-port
      server:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - adventurelog-backend.jnobrega.com
        rules:
          - backendRefs:
              - name: *app
                port: *server-port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /code/media
