# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adventurelog
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  uninstall:
    keepHistory: false
  values:
    controllers:
      adventurelog:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.3@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
              pullPolicy: IfNotPresent
            envFrom: &secret
              - secretRef:
                  name: adventurelog-secret
        containers:
          frontend:
            image:
              repository: ghcr.io/seanmorley15/adventurelog-frontend
              tag: latest@sha256:6db530248f958ceacdee4e42f9f3f816bc9bbd3710336cde8f1e5859d5cf7aee
            env:
              PUBLIC_SERVER_URL: "http://adventurelog.default.svc.cluster.local:8000"
              BODY_SIZE_LIMIT: Infinity
              ORIGIN: "https://adventurelog.jnobrega.com"
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
          server:
            image:
              repository: ghcr.io/seanmorley15/adventurelog-backend
              tag: latest@sha256:8e2201f5faf4fef531c692fc3ed6492445d2c0a849a09379c9f6f7e4bbbf53ad
            env:
              PUBLIC_URL: https://adventurelog-backend.jnobrega.com
              FRONTEND_URL: https://adventurelog.jnobrega.com
              CSRF_TRUSTED_ORIGINS: https://adventurelog-backend.jnobrega.com,https://adventurelog.jnobrega.com
              DEBUG: "true"
              DJANGO_ADMIN_USERNAME: admin
              ENABLE_RATE_LIMITS: "true"
            envFrom: *secret
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 125m
                memory: 500Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &frontend-port 3000
          base:
            port: &server-port 8000
    route:
      frontend:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - adventurelog.jnobrega.com
        rules:
          - backendRefs:
              - name: *app
                port: *frontend-port
      server:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - adventurelog-backend.jnobrega.com
        rules:
          - backendRefs:
              - name: *app
                port: *server-port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /code/media
