config:
  envoyGateway:
    provider:
      type: Kubernetes
      kubernetes:
        deploy:
          type: GatewayNamespace
    extensionApis:
      enableBackend: true
global:
  imageRegistry: mirror.gcr.io
