machine:
  network:
    interfaces:
      - deviceSelector:
          hardwareAddr: "c4:65:16:16:e2:b8"
          physical: true
        dhcp: true
        dhcpOptions:
          routeMetric: 1024
        mtu: 1500
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.1.139
  - address: 1.1.1.1
searchDomains:
  disableDefault: true
