# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: pg-backup-s3
spec:
  image: ghcr.io/jdavid77/pg-backup-s3
  interval: 5m
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: &repo pg-backup-s3
spec:
  imageRepositoryRef:
    name: *repo
  filterTags:
    pattern: '^pg18-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
