apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github-mcp
spec:
  headersFrom:
  - name: Authorization
    valueFrom:
      type: Secret
      name: github-mcp-server
  protocol: STREAMABLE_HTTP
  terminateOnClose: true
  timeout: 5s
  url: https://api.githubcopilot.com/mcp/
