apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: flux-mcp
  namespace: automation
spec:
  transportType: http
  httpTransport:
    targetPort: 9090
  deployment:
    image: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp:v0.45.1
    port: 9090
    serviceAccountName: flux-mcp
    args:
      - serve
      - --transport=http
      - --port=9090
      - --read-only=true
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 64Mi
    env:
      RUNTIME_NAMESPACE: "automation"
