# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/ate.dev/sandboxconfig_v1alpha1.json
apiVersion: ate.dev/v1alpha1
kind: SandboxConfig
metadata:
  name: gvisor-default
spec:
  sandboxClass: gvisor
  default: true
  pauseImage: "registry.k8s.io/pause:3.10.2@sha256:f548e0e8e3dc1896ca956272154dde3314e8cc4fde0a57577ee9fa1c63f5baf4"
  assets:
    amd64:
      runsc:
        url: "gs://gvisor/releases/nightly/2026-06-02/x86_64/runsc"
        sha256: "efd12935f6654c91a1389710eb8dfa4d12b6b9be00db87526dc2eb584ad00119"
