# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/ate.dev/workerpool_v1alpha1.json
apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  name: default
  namespace: automation
spec:
  replicas: 2
  ateomImage: ghcr.io/kagent-dev/substrate/ateom-gvisor:v0.0.12
