# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: opentelemetry-operator
    namespace: flux-system
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: v0.155.0@sha256:f50a8ef294c6e6f7b6335aaa715d88279ec02d0729c4c3d7d7d290b054754c31
      collectorImage:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
        tag: 0.156.0@sha256:84036a61f0ee4a7aaa62f357a822ec2738b81a986d70fe12ff23fefce34ae8d1
    admissionWebhooks:
      certManager:
        enabled: false
