# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: opentelemetry-operator
    namespace: flux-system
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: v0.156.0@sha256:5ff32ebb65accc207ac9d0dbf6a9d362175f6d70829d697ea5264e33054bc674
      collectorImage:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
        tag: 0.157.0@sha256:4eb842091c796156d4d3c994eb22ba793590f5723719dbf6b8436cb4dfc17f48
    admissionWebhooks:
      certManager:
        enabled: false
