# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  interval: 15m
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: opentelemetry-operator
    namespace: flux-system
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: v0.151.0@sha256:9f809b6ae5ffb28428ee1508c9268a77ebedd82de08c851fb9de7cc3f5bc7b31
      collectorImage:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
        tag: 0.152.1@sha256:c68d838080b5d108ed1203716783465511f3a86ae2b039342ac578d2b4e82979
    admissionWebhooks:
      certManager:
        enabled: false
