# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.19.2@sha256:f68e959bf66f4f458893ea58facac71690fe6f2ac7a31466b5cecb41b4e99c02
            env:
              BASE_URL: https://food.jnobrega.com
              ALLOW_SIGNUP: false
              API_DOCS: true
              TZ: Europe/Lisbon
              PUID: 1000
              PGID: 1000
              DB_ENGINE: postgres
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9000
    route:
      main:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - food.jnobrega.com
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
