apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-secret
  namespace: media
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /booklore/db
      metadataPolicy: None
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: booklore-secret
    template:
      engineVersion: v2
      mergePolicy: Replace