# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/kagent.dev/remotemcpserver_v1alpha2.json
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github-mcp
spec:
  headersFrom:
  - name: &header Authorization
    valueFrom:
      type: Secret
      name: github-mcp-secret
      key: *header
  - name: X-MCP-Toolsets
    value: "repos,pull_requests,context,git"
  description: "GitHub MCP Server"
  protocol: STREAMABLE_HTTP
  terminateOnClose: true
  timeout: 5s
  url: https://api.githubcopilot.com/mcp/
