# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/main/config.schema.json

prometheus: http://prometheus-operated.monitoring.svc.cluster.local:9090

badges:
  - id: talos_version
    colorExpr: '"orange"'
    icon: si:talos
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    title: Talos
    valueExpr: labels["version_id"]

  - id: kubernetes_version
    colorExpr: '"#0e63eb"'
    icon: si:kubernetes
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    title: Kubernetes
    valueExpr: labels["git_version"]

  - id: flux_version
    colorExpr: '"#07ddf5"'
    icon: si:flux
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    title: Flux
    valueExpr: labels["revision"]

  - id: cluster_age_days
    colorExpr: 'colorScale(result, [15552000.0, 31104000.0], ["green", "orange", "red"])'
    query: round(time() - min(kube_node_created))
    title: Age
    valueExpr: humanizeDurationDays(result)

  - id: cluster_uptime_days
    colorExpr: 'colorScale(result, [15552000.0, 31104000.0], ["green", "orange", "red"])'
    query: round(avg(node_time_seconds{pod!=""} - node_boot_time_seconds{pod!=""}))
    title: Uptime
    valueExpr: humanizeDurationDays(result)

  - id: cluster_alert_count
    query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
    colorExpr: 'colorScale(result, [1.0], ["green", "red"])'
    title: Alerts
