apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
  dataEngine: v1
  nodeSelector: storage
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: longhorn-snapshot
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
  dataEngine: v1
  nodeSelector: storage
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: longhorn-cache
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-zot
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataLocality: "strict-local"
  dataEngine: v1
  nodeSelector: storage
volumeBindingMode: WaitForFirstConsumer
