apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret curve-tracker-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    name: *secret
  dataFrom:
    - extract:
        key: /curve/google
