# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana-service-account-token
spec:
  refreshInterval: 5m
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - name: akeyless-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: grafana-service-account-token
  template:
    engineVersion: v2
    data:
      GRAFANA_SERVICE_ACCOUNT_TOKEN: "{{ .token }}"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: /grafana/service-account-token
          property: token
