---
# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-service-account
spec:
  instanceName: grafana
  name: grafana-service-account
  role: Admin
  tokens:
    - name: grafana-service-account-token
      secretName: grafana-service-account-token
