# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/valkey.io/valkeycluster_v1alpha1.json
# Dragonfly required me to setup the nodes manually in cluster mode.
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: valkey-${APP}
spec:
  shards: 1
  replicas: 2
  workloadType: StatefulSet
  persistence:
    size: 1Gi
    storageClassName: longhorn
    reclaimPolicy: Retain
  config:
    cluster-node-timeout: "5000"
    appendonly: "yes"
    protected-mode: "no"
  containers:
    - name: server
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      # when a pod is rescheduled and gets a new IP
      # the nodes.conf persisted on each PVC has the old IP hardcoded
      # it required manual intervention using CLUSTER MEET
      # Passing the new required args via command to make use of POD_NAME
      args:
        - --cluster-announce-hostname
        - $(POD_NAME).valkey-valkey-${APP}.ate-system.svc.cluster.local
        - --cluster-preferred-endpoint-type
        - hostname
  podDisruptionBudget:
    mode: Cluster
  scheduling:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
