# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ScaledObject
    patch: |
      - op: add
        path: /spec/advanced/scalingModifiers
        value:
          formula: "trig_nfs * trig_postgres"
          target: "1"
          activationTarget: "0"
