# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/keda.sh/triggerauthentication_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: ${APP}-pg-auth
spec:
  secretTargetRef:
    - key: CONNECTION_STRING
      name: ${SECRET_NAME:=${APP}-secret}
      parameter: connection
